SELECT
    OS.CUSTOMERID,
    C.CUSTOMERNAME,
    SUM(OS.ORDERCOUNT) AS ORDERCOUNT,
    SUM(OS.REVENUE) AS REVENUE
FROM
    {{ ref('ORDER_FACT')}} OS
JOIN
    {{ ref('CUSTOMER_STG')}} C
ON OS.CUSTOMERID = C.CUSTOMERID
GROUP BY
    OS.CUSTOMERID,
    C.CUSTOMERNAME