SELECT A.PRODUCTID, B.UNITPRICE, A.QUANTITY, (B.UNITPRICE * A.QUANTITY) AS TOTALPRICE
FROM {{ source('processing','proSal') }} A
JOIN {{ source('landing','ordItms')}} B ON A.PRODUCTID = B.PRODUCTID
ORDER BY TOTALPRICE DESC