SELECT
    OS.STOREID,
    SUM(OFACT.REVENUE) AS ACTUALSALES,
    SUM(ST.SALESTARGET) AS TARGETSALES,
    CONCAT(ROUND((ACTUALSALES / TARGETSALES) * 100,2), ' %') AS SALESPERCENTAGE
FROM
    {{ ref('ORDER_STG')}} OS
JOIN
    {{ ref('ORDER_FACT')}} OFACT
ON OS.ORDERID = OFACT.ORDERID
JOIN
    {{ ref('SALESTARGET')}} ST 
ON ST.STOREID = OS.STOREID
GROUP BY 1