WITH BASE AS (
    SELECT 'BEST SELLING PRODUCT' AS TITLE, PRODUCTID, TOTALPRICE AS TOTALPRICE
    FROM {{source('consumption','proPerf')}}
    WHERE TOTALPRICE = (SELECT MAX(TOTALPRICE) FROM {{source('consumption','proPerf')}})
    UNION
    SELECT 'LEAST SELLING PRODUCT' AS TITLE, PRODUCTID, MIN(TOTALPRICE) AS TOTALPRICE
    FROM {{source('consumption','proPerf')}}
    WHERE TOTALPRICE = (SELECT MIN(TOTALPRICE) FROM {{source('consumption','proPerf')}})
    GROUP BY PRODUCTID, TOTALPRICE
)
SELECT A.TITLE,A.PRODUCTID,B.NAME, A.TOTALPRICE
FROM BASE A
JOIN {{source('landing','product')}} B ON A.PRODUCTID = B.PRODUCTID
ORDER BY A.TITLE